Инкремент 13
Fairness2/gmetrics pull request #13
Opened 2024-08-09 19:52 UTC by Fairness2

Добавил работу с ошибками. Улучшена устойчивость отправки метрик путем добавления повторной отправки при ошибках соединения с сервером или с базой данных.

2024-08-17 07:04 UTC, vokinneberg requested changes
Ура, первое ревью третьего спринта! 🎉 В этом спринте наше приложение стало еще сложнее, добавился новый слой БД 💪 Ты реализовал доработки сервиса в соответствии с постановкой задачи. Отличная работа! 🚀 Тем не менее мне хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Ты консистентно встроил функционал в структуру существующего приложения. 👍
3. Ты реализовал тесты новых сценариев и дополнил существующие. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Мне кажется, по условию задачи DB сторадж должен работать так же, как и файловый в смысле синхронизации. Кажется, для DB реализовано только синхронное сохранение? Стоит реализовать асинхронное.
2. Не стоит возвращать конкретный тип ошибки. Стоит реализовать кастомную ошибку так, чтобы она реализовывала интерфейс error и возвращать его, а на вызывающей стороне можно будет использовать [[errors.As](http://errors.as/)](http://errors.as/)(...) для проверки.

2024-08-17 07:04 UTC, vokinneberg commented on cmd/agent/collector/sender/sender.go
> +func (c *Client) sendMetrics() error {
👍 метод стал гораздо проще!

2024-08-17 07:04 UTC, vokinneberg commented on cmd/agent/collector/sender/sender.go
> +	log.Println("Sending metrics")
Было бы здорово попробовать все-таки использовать структурное логирование - `slog` или `zap`.

2024-08-17 07:04 UTC, vokinneberg commented on cmd/server/config/config.go
> +		StoreInterval: int64(DefaultStoreInterval),
Не очень красиво, как пом мне делать приведение здесь. Может быть стоит сразу определить тип?

2024-08-17 07:04 UTC, vokinneberg commented on cmd/server/handlers/handlemetric/jsonmanyhandler_test.go
> +			assert.Equal(t, test.wantStatus, res.StatusCode())
Стоит добавить информативное сообщение к ассертам с информацией о том, что ожидалось и что пошло не так.

2024-08-17 07:04 UTC, vokinneberg commented on cmd/server/handlers/handlemetric/service.go
> +			return "", &UpdateMetricError{err, http.StatusInternalServerError}
👍 за реализацию кастомных ошибок!

2024-08-17 07:04 UTC, vokinneberg commented on cmd/server/handlers/handlemetric/service.go
> +func updateMetricsByRequestBody(bodies []payload.Metrics) (string, *UpdateMetricError) {
Не стоит возвращать конкретный тип ошибки. Стоит реализовать кастомную ошибку так, чтобы она реализовывала интерфейс error и возвращать его, а на вызывающей стороне можно будет использовать errors.As(...) для проверки.
```suggestion
func updateMetricsByRequestBody(bodies []payload.Metrics) (string, error) {
```

2024-08-17 07:04 UTC, vokinneberg commented on cmd/server/handlers/handlemetric/service.go
> +	return "Metrics successfully updated.", nil
 Мне кажется лишним возвращать информационное сообщение, как параметр из функции. Думаю там, где функция вызывается можно просто использовать сообщение для записи в лог, если нужно. Возвращаемые параметры лучше определять функциональными - относящимися к тому, что делает функция. В крайнем случае, если хочется добавить индикацию того, что функция выполнилась успешно, можно добавить  bool параметр.

2024-08-17 07:04 UTC, vokinneberg commented on cmd/server/handlers/ping/handler.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
👍 за установку таймаута.

2024-08-17 07:04 UTC, vokinneberg commented on cmd/server/handlers/ping/handler.go
> +	helpers.SetHTTPError(response, http.StatusOK, []byte{})
У меня название этого метода не бьется с тем, что он делает. Наверное стоит дать ему более информативное название?
```suggestion
	helpers.SetHTTPReponse(response, http.StatusOK, []byte{})
```

2024-08-17 07:04 UTC, vokinneberg commented on cmd/server/main.go
> +	if err = runApplication(wg); err != nil {
На мой взгляд не совсем удачное использование `errgroup.Group`, так как не видно, как она вызывается. Мне кажется стоит сделать вызовы видимым, либо использовать `wg.Wait()` там, где вызывается `Go(...)` и адаптировать код для этого.
```suggestion
	wg.Go(func() error { return runApplication() })
```

2024-08-17 07:04 UTC, vokinneberg commented on cmd/server/main.go
> +				return store.Sync(ctx)
Мне кажется по условию задачи DB сторадж должен работать так же как и файловый в смысле синхронизации. Кажется для  DB реализовано только синхронное сохранение?

2024-08-17 07:04 UTC, vokinneberg commented on cmd/skill/app.go
> +func (a *app) webhook(response http.ResponseWriter, request *http.Request) {
Метод получился безумно длинный. Стоит подумать о том чтобы разбить его на несколько более коротких методов. Кажется быть стоит рассмотреть возможность использования паттерна visitor или command?

2024-08-17 07:04 UTC, vokinneberg commented on cmd/skill/app.go
> +	/*text := "Для вас нет новых сообщений."
Очень длинный метод, и закомментированный код делает чтение еще сложнее.

2024-08-17 07:04 UTC, vokinneberg commented on internal/metrics/DBStorage.go
> +func NewDBStorage(ctx context.Context, db *sql.DB) (*DBStorage, error) {
Думаю, раз мы определили интерфейс мы хотим его принимать и как параметр тоже?
```suggestion
func NewDBStorage(ctx context.Context, db SQLExecutor) (*DBStorage, error) {
```

2024-08-17 07:04 UTC, vokinneberg commented on internal/metrics/DBStorage.go
> +// Get Получение значения метрики из хранилища
Думаю стоит либо определить godoc комментарии для всех методов либо не определять их вовсе, в противном случае как-то не аккуратно.

2024-08-17 07:04 UTC, vokinneberg commented on internal/metrics/FileStorage.go
> +				logger.Log.Debug("Error while syncing metrics")
Есть ли причина почему это `Debug`? Думаю ошибку стоит залогировать хотя бы на уровне `Warn`?

2024-08-17 07:04 UTC, vokinneberg commented on internal/metrics/Metrics.go
> +func (g *Gauge) Scan(value interface{}) error {
Сейчас есть алиас `any` для `interface{}`, мне кажется он предпочтительней.
```suggestion
func (g *Gauge) Scan(value any) error {
```

2024-08-17 07:04 UTC, vokinneberg commented on internal/store/skill/pg/store.go
> +	tx, err := s.conn.BeginTx(ctx, nil)
 👍 за исползование транзакции!

2024-08-17 17:24 UTC, Fairness2 commented on cmd/agent/collector/sender/sender.go
> +	log.Println("Sending metrics")
На агенте сделал такой же лог, как на сервере

2024-08-17 17:26 UTC, Fairness2 commented on cmd/server/config/config.go
> +		StoreInterval: int64(DefaultStoreInterval),
Определил дефолтную переменную как int64

2024-08-17 18:29 UTC, Fairness2 commented on cmd/server/handlers/handlemetric/jsonmanyhandler_test.go
> +			assert.Equal(t, test.wantStatus, res.StatusCode())
Добавил описание что произошло

2024-08-17 18:44 UTC, Fairness2 commented on cmd/server/handlers/handlemetric/service.go
> +func updateMetricsByRequestBody(bodies []payload.Metrics) (string, *UpdateMetricError) {
Сделал возвращение ошибки, а в вызывающей функции проверяю через errors.As

2024-08-17 18:50 UTC, Fairness2 commented on cmd/server/handlers/handlemetric/service.go
> +	return "Metrics successfully updated.", nil
Убрал возвращение текста, теперь он ставится вызывающей функцией при нулевой ошибке

2024-08-17 18:52 UTC, Fairness2 commented on cmd/server/handlers/ping/handler.go
> +	helpers.SetHTTPError(response, http.StatusOK, []byte{})
Функция переросла первоначальный смысл, переименовал

2024-08-17 19:05 UTC, Fairness2 commented on internal/metrics/DBStorage.go
> +func NewDBStorage(ctx context.Context, db *sql.DB) (*DBStorage, error) {
Сделал принимающий параметр интерфейсом

2024-08-17 19:17 UTC, Fairness2 commented on cmd/server/main.go
> +	if err = runApplication(wg); err != nil {
Сделал использование группы только в одном методе

2024-08-17 20:18 UTC, Fairness2 commented on cmd/server/main.go
> +				return store.Sync(ctx)
Конечно про это ничего не сказано в задании. Но для усложнения задачи сделал)

2024-08-17 20:43 UTC, Fairness2 commented on cmd/skill/app.go
> +func (a *app) webhook(response http.ResponseWriter, request *http.Request) {
Разбил обработки на подфункции

2024-08-17 20:43 UTC, Fairness2 commented on cmd/skill/app.go
> +	/*text := "Для вас нет новых сообщений."
Удалил закомментированный код

2024-08-17 20:44 UTC, Fairness2 commented on internal/metrics/FileStorage.go
> +				logger.Log.Debug("Error while syncing metrics")
СОгласен, переделал на Warn

2024-08-17 21:03 UTC, Fairness2 commented on internal/metrics/DBStorage.go
> +// Get Получение значения метрики из хранилища
Поправил комментарии

2024-08-17 21:03 UTC, Fairness2 commented on internal/metrics/Metrics.go
> +func (g *Gauge) Scan(value interface{}) error {
Поправил

2024-08-22 03:45 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью третьего спринта! 🙌  Отличная работа! 🚀 

2024-08-22 07:21 UTC, merged