Инкремент 5
Fairness2/gmetrics pull request #5
Opened 2024-07-08 17:42 UTC by Fairness2

Добавлена поддержка конфигурации из переменных окружения

2024-07-16 19:12 UTC, vokinneberg requested changes
Поздравляю с завершением первого спринта и первым ревью! 🤗 Твой код хорошо структурирован, покрыт тестами, работает и проходит тесты. Отличная работа! 🚀

**Сильные стороны твоего PR:**

- **Функциональность:**Код функционален и корректен! 🚀
- **Тестирование:**Реализованы тесты базовых сценариев и дополнительные тесты. В тестах есть развернутые сообщения о том, что пошло не так. 👍
- **Структура сервиса:**По условию задания структура сервиса должна представлять собой набор пакетов и структур, разделённых на слои. Код хорошо структурирован и разбит на отдельные компоненты и пакеты. 👍
- **Реализация интерфейсов:** Слой`storage`должен имплементировать интерфейс хранения, например`repositories`. Ты реализовал интерфейс, но я посоветовал бы определить его там, где он используется, а не рядом с реализацией.

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- **Сложность:** Мне показалось, что в некоторых местах твой код сложнее, чем мог бы быть. Например, использования рефлексии для получения имен метрик я бы избегал.
- **Глобальные переменные и метод**`init()`: Не стоит использовать инициализацию при помощи метода init(), если это явно не требуется, как в случае с темплейтами.
- **Синхронизация доступак хранилищу**. Ты реализовал синхронизацию доступа к хранилищу клиента, но не сервера. Стоит подумать, как будет себя вести код при конкурентной обработке нескольких запросов на сервере и как можно синхронизировать доступ к хранилищу.
- **Логирование:** Я бы советовал использовать либо логгер из пакета`log`, либо из пакета`slog`для структурного логирования.
- **Комментарии:** Было бы здорово, если бы ты добавил комментарии в коде там, где есть сложные места, которые требуют пояснения, а также для публичных методов.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/config/env.go
> +var ServerURL = "http://localhost:8080"
 Значения по-умолчанию можно объявить как константы. Не обязательно использовать `time.Duration(10)`, так как умножение `2 * time.Second`  так же даст тип `Duration`.

```suggestion
const (
	// PollInterval Интервал между сборкой данных
	PollInterval = 2 * time.Second

	// ReportInterval Интервал между отправкой данных
	ReportInterval = 10 * time.Second

	// ServerURL Url сервера получателя метрик
	ServerURL = "http://localhost:8080"
)
```

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/config/env.go
> +func Parse() {
Мне кажется, что использование глобальных переменных, которые устанавливаются после парсинга параметров командной строки и переменных окружения, слишком сложное. Предлагаю вариант, при котором метод `Parse(...)` возвращает инициализированную структуру конфига, а глобальные константы используются как значения по умолчанию. Логично, если параметры командной строки будут переопределять значения переменных окружения.

```go
type Config struct {
		PollInterval   int    `env:"POLL_INTERVAL" envDefault:"-2"`
		ReportInterval int    `env:"REPORT_INTERVAL" envDefault:"-2"`
		ServerURL      string `env:"ADDRESS"`
}

func Parse() *Config {
	...
}
```

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/config/env.go
> +		log.Print(err)
Я бы рекомендовал вернуть ошибку в вызывающий код и там принять решение о том, как ее обрабатывать.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/config/env.go
> +		_ = setServerURL(cnf.ServerURL)
Не стоит игнорировать ошибку. Я бы рекомендовал обработать ошибку и вернуть ее в вызывающий код и там принять решение о том, как ее обрабатывать.

```suggestion
		if err := setServerURL(cnf.ServerURL); err != nil {
		        return fmt.Errof("set server URL: %v", err)
		}
```

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/config/env.go
> +		PollInterval = time.Duration(val) * time.Second
Можно упростить выражение.

```suggestion
		PollInterval = val * time.Second
```

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/main.go
> +	}*/
Не стоит оставлять закомментированный код, так как он засоряет кодовую базу. Если это необходимо, стоит добавить комментарий с объяснением, почему данный код нужен.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/main.go
> +	time.Sleep(30 * time.Second)
Не совсем понимаю какое назначение у этого таймера? Если он нужен для того чтобы ожидать выполнения, сбора метрик и из отправки, то это таймер сработает через 30 секунд и приложение закончит работу. Здесь стоит использовать другие средства синхронизации - рассмотри возможность использования каналов или  waitGroup.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/main.go
> +package collector
Вообще по конвенции Go файл `main.go` - это файл, который содержит точку входа в приложение - функцию main. Поэтому лучше во избежание путаницы выбрать для это файла другое имя.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/main.go
> +func collectProcess() {
В этом методе не хватает завершения цикла. Попробуй сделать завершение при помощи `context`  cancellation.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/collection/collection.go
> +func (c *CollectionType) UnlockRead() {
Что здесь все-таки предполагается вызывать? Если `Unlock(...)`, то использование `sync.RWNutex` не совсем обосновано, так как его методы нигде не используются. К тому же по логике реализации похоже, что все-таки здесь предполагается использовать  `RUnlock(...)`?

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/collection/collection.go
> +func init() {
Не рекомендую использовать метод `init()` для инициализации коллекции. Думаю, стоит создавать коллекцию в момент инициализации агента, а mutex можно сделать частью самой коллекции.

`init()` функции могут быть полезны для статической инициализаци конфигурации на уровне пакета, например. Но не стоит их использовать для создания инстансов структур и т.д. так как это может затруднить и отладку и тестирование.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/collection/collection.go
> +	fmt.Println("End collecting metrics")
Я бы рекомендовал использовать логгер либо из пакета `log` либо из пакета `slog` вместо `fmt.Println(...)`.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/main.go
> +	fmt.Println("New sender client created")
Я бы рекомендовал использовать логгер либо из пакета `log` либо из пакета `slog` вместо `fmt.Println(...)`.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/sender/sender.go
> +func (c *Client) StartSender() {
Не совсем понятно назначение метода-обертки `StartSender(...)`. Мне кажется будет проще сделать метод `periodicSender()` публичным, и вызывать его напрямую. Так же не стоит вызывать горутину не явно внутри другого метода - это может ввести в заблуждение о природе работы метода.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/sender/sender.go
> +	v := reflect.Indirect(reflect.ValueOf(c.metricsCollection))
Рефлексия это мощный и в то же время опасный механизм. В общем случае не стоит использовать рефлексию там, где можно без нее обойтись. Здесь можно попробовать использовать мапу `map[string]int64` внутри коллекции для сборка метрик и потом отправлять метрики используя ключ - значение, которые хранятся в мапе.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/sender/sender_test.go
> +			name: "invalid http status",
Не стоит использовать одинаковые имена для именования тестов. Лучше дать им более информативные названия, описывающие, что делает тест.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/sender/sender_test.go
> +			name: "successful metric send",
Небольшая рекомендация по именованию тестов - Go автоматически заменяет пробелы на подчерки в названиях тестов. Поэтому я бы не рекомендовал использовать пробелы в названиях или сразу заменять из на подчерки - это позволит избежать проблем про поиске упавших тестов.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/agent/collector/sender/sender_test.go
> +				assert.Error(t, err)
В общем-то в использовании сторонних assert  библиотек нет ничего неправильного, но разработчики Go не рекоменду использовать сторонние assert библиотеки, так как _это либо останавливает тест раньше времени (если вызовы используют t.Fatalf или panic), либо упускает интересную информацию о том, что тест сделал правильно. Это также заставляет assert библиотеку создавать совершенно новый подъязык вместо использования существующего языка программирования (самого Go)._ https://go.dev/wiki/TestComments

2024-07-16 19:12 UTC, vokinneberg commented on cmd/server/config/config.go
> +func Parse() {
Предлагаю тут использовать такую же схему, как для создания конфига агента при котором метод `Parse(...)` возвращает инициализированную структуру конфига, а глобальные константы используются как значения по умолчанию.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/server/main.go
> +		panic(err)
Не стоит использовать панику, так как она приводит к крашу приложения. Рекомендую вызвать `log.Fatalf(...)`, которая выведет сообщение об ошибке и завершит процесс при помощи вызова `os.Exit(1)`.

2024-07-16 19:12 UTC, vokinneberg commented on internal/metrics/MemStorage_test.go
> +		wantValue interface{}
Можно заменить тип `interface{}` на тип `any`. Это синонимы, но второй предпочтительнее именно из за своего имени.

2024-07-16 19:12 UTC, vokinneberg commented on internal/metrics/MemStorage.go
> +type Storage interface {
👍 за реализацию интерфейса. Я бы рекомендовал попробовать определить интерфейс не рядом с реализацией, а рядом с тем местом, где он используется. Это позволит следовать принципам   Dependency Inversion и interface Segregation.

2024-07-16 19:12 UTC, vokinneberg commented on internal/metrics/MemStorage_test.go
> +func TestNewMemStorage(t *testing.T) {
👍 за реализацию теста хранилища.

2024-07-16 19:12 UTC, vokinneberg commented on internal/metrics/MemStorage.go
> +func init() {
Опять же не рекомендую использовать метод `init()` для инициализации коллекции. Думаю, стоит создавать коллекцию в момент инициализации сервера.

`init()` функции могут быть полезны для статической инициализаци конфигурации на уровне пакета, например. Но не стоит их использовать для создания инстансов структур и т.д. так как это может затруднить и отладку и тестирование.

Предлагаю просто вызывать в момент инициализации приложения `NewMemStorage()` и передавать инстанс в хэндлер.

Это пока не обязательно, но в агента реализована синхронизация, а здесь нет. Предлагаю подумать нужна ли она здесь?

2024-07-16 19:12 UTC, vokinneberg commented on internal/metrics/MemStorage.go
> +func (storage *MemStorage) SetGauge(name string, value Gauge) {
Названия методов не совсем консистентные. Add -> Set - думаю стоит использовать либо то, либо другое.

2024-07-16 19:12 UTC, vokinneberg commented on internal/helpers/helpers_test.go
> +			defer result.Body.Close()
Стоит закрывать тело ответа сразу после полкчения, так как если assert остановит тест он так и останется не закрытым.
```suggestion
			result := response.Result()
			defer result.Body.Close()
			
			assert.Equal(t, c.mockStatus, result.StatusCode)
```

2024-07-16 19:12 UTC, vokinneberg commented on cmd/skill/main_test.go
> +		{method: http.MethodGet, expectedCode: http.StatusMethodNotAllowed, expectedBody: ""},
Рекомендую добавить более информативные наименования для тестов.

2024-07-16 19:12 UTC, vokinneberg commented on cmd/server/handlers/getmetrics/handler.go
> +func init() {
Пожалуй единственное место, где оправдано использование `init()`, так как лучше чтобы шаблон был скомпилирован единожды. 
Правда не совсем понимаю назначение использования мапы, так как тут используется только один шаблон?

2024-07-16 19:12 UTC, vokinneberg commented on cmd/server/handlers/getmetrics/handler_test.txt
> +package getmetrics
Мне кажется тут не корректное расширение у файла?

2024-07-16 19:12 UTC, vokinneberg commented on cmd/skill/main.go
> +	if request.Method != http.MethodPost {
Не совсем понятно зачем нужен этот вебхук - chi должен обработать такую ситуацию автоматически.

2024-07-16 19:50 UTC, Fairness2 commented on cmd/agent/main.go
> +	time.Sleep(30 * time.Second)
Тут поставил таймер, так как с ожидание ввода, что закомментирован ниже, не проходили тесты, так как сервер работал слишком долго и не завершал свою работу. Я бы хотел убрать таймер и расскоментировать код с завершением по вводу пользователя, но тесты не пройдут

2024-07-16 19:51 UTC, Fairness2 commented on cmd/agent/main.go
> +	}*/
Он оставлен, так как является лушим вариантом, чем таймер на время работы выше, но без таймера не проходят тесты

2024-07-16 19:57 UTC, Fairness2 commented on cmd/server/handlers/getmetrics/handler_test.txt
> +package getmetrics
Я написал тест, но из-за того, что при инициализации темплейтов используются относительные пути, то при тестах в гите тест падал, так как он запускается используюя корневую папку - папку с тестом, а не папку проекта. Решил оставить решение на потом, и изменил расширение файла, чтобы он не попал в компиляцию

2024-07-17 14:10 UTC, Fairness2 commented on cmd/agent/config/env.go
> +		PollInterval = time.Duration(val) * time.Second
Не получится, компилятор жалуется на то, что не может спарсить инт в продолжительность 
![image](https://github.com/user-attachments/assets/ccb28395-bfe2-4b63-aea1-6d297a8d74d0)

2024-07-17 19:19 UTC, Fairness2 commented on cmd/agent/collector/sender/sender_test.go
> +				assert.Error(t, err)
В дальнешем буду стараться использовать чистый го, по опыту других языков привычнее пользоваться асертами просто

2024-07-17 19:37 UTC, Fairness2 commented on internal/metrics/MemStorage.go
> +func (storage *MemStorage) SetGauge(name string, value Gauge) {
Я исходил из того, что Gauge мы перезаписываем, поэтому set, а Counter мы добавляем к существующему, поэтому Add

2024-07-17 19:50 UTC, Fairness2 commented on cmd/server/handlers/getmetrics/handler.go
> +func init() {
На случай, если ещё шаблоны понадобятся, но в данном случае это излишне, согласен

2024-07-17 19:53 UTC, Fairness2 commented on cmd/skill/main.go
> +	if request.Method != http.MethodPost {
Это в качестве примера в уроке по построению умения для алисы было, а так как тут не используется chi, то использование для ограничения метода оправдано🤔

2024-07-18 23:31 UTC, vokinneberg commented on cmd/agent/config/env.go
> +		PollInterval = time.Duration(val) * time.Second
Действительно, это работает только с литералом `PollInterval = 10 * time.Second`. Моя шибка 👍

2024-07-19 00:33 UTC, vokinneberg approved these changes
Костя, привет! 👋 Мне показалось, что ты не учёл все мои замечания. Действительно, большинство из них имеют рекомендательный характер, но было бы здорово, если бы ты оставил свои комментарии к ним 😊 Здорово, что ты разобрался с синхронизацией и задумался о завершении приложения. Я добавил несколько комментариев с предложениями о том, как можно улучшить механизмы, которые ты добавил 👍 Тем не менее, мне всё ещё кажется, что с твоей реализацией можно немного поработать и сделать несколько улучшений или хотя бы обсудить их. Обязательно приходи на встречу 1 на 1 в следующем спринте, и мы бы обсудили и те комментарии, на которые ты не ответил, и новые комментарии тоже 🙌

Поздравляю с завершением первого спринта и завершением первого ревью! 🤗 Отличная работа! 🚀 И удачи на втором спринте 💪

2024-07-19 00:33 UTC, vokinneberg commented on cmd/agent/collector/collection/collection.go
> +	mutex *sync.Mutex
Получается в твоем случае доступ на запись  к коллекции будет блокироваться при каждом чтении. Это конечно будет не заметно при запуске тестов, но в случае более-менее серьезной нагрузки это станет проблемой. Думаю можно оставить этот момент для обсуждения до того времени, когда на курсе будет затрагиваться тема конкурентности/многопоточности.

2024-07-19 00:33 UTC, vokinneberg commented on cmd/agent/config/env.go
> +func InitializeNewCliConfig() *CliConfig {
Возможно стоит переименовать в `InitializeDefaultConfig`, мне кажется это будет больше соответствовать назначение функции?

2024-07-19 00:33 UTC, vokinneberg commented on cmd/agent/config/env.go
> +var Params *CliConfig
Это безусловно твое решение использовать глобальную переменную для хранения конфигурации. По моему опыту с глобальными переменными могут возникать различные неприятные ситуации, но в нашем случае я думаю это не страшно. Тем не менее на будущее я бы рекомендовал попробовать упростить работу с конфигом - мне показалось что реализация немного переусложнена.

2024-07-19 00:33 UTC, vokinneberg commented on cmd/agent/collector/collection/initializer.go
> +func CollectProcess(ctx context.Context) {
👍 за использование контекста для управления жизненным циклом функции!

2024-07-19 00:33 UTC, vokinneberg commented on cmd/agent/collector/collection/initializer.go
> +	}
Тут можно немного оптимизировать, предлагаю рассмотреть такой вариант:

```suggestion
        for {
		// Ловим закрытие контекста, чтобы завершить обработку
		select {
		case <-time.After(config.Params.PollInterval):
			stats := runtime.MemStats{}
			runtime.ReadMemStats(&stats)
			Collection.Collect(stats)
		case <-ctx.Done():
			log.Printf("Collect metrics process stopped: %v\n", ctx.Err())
			return
		}
	}
```

2024-07-19 00:33 UTC, vokinneberg commented on cmd/agent/main.go
> +	wg.Wait() // Ожидаем завершения всех горутин
Ты правильно разобрался с `WaitGroup`, это очень здорово! 👍 Могу предложить небольшое улучшение, которое поможет решить несколько проблем. Во-первых ты создал контекст с таймаутом и соотвественно он отмениться через 30 секунд и агент прекратит свою работу, а нам нужно чтобы он работал пока мы его не решили завершить принудительно. Я реализовал завершения по нажатию Ctrl+C в консоли или по отправке `SIGTERM`. 

```suggestion
ctx, cancel := context.WithCancel(context.Background()) // Таймер, чтобы ограничить время работы агента, чтобы пройти тесты
	defer cancel()

	var wg sync.WaitGroup
	wg.Add(2)

	// Создаём новую коллекцию метрик и устанавливаем её глобально
	collection.Collection = collection.NewCollection()
	go func() {
		defer wg.Done()
		collection.CollectProcess(ctx)
	}()

	// Запускаем отправку данных
	client := sender.NewSender(collection.Collection)
	go func() {
		defer wg.Done()
		client.PeriodicSender(ctx)
	}()

	// Ожидаем сигнала завершения Ctrl+C, чтобы корректно завершить работу
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, syscall.SIGINT, syscall.SIGTERM)
	<-stop

	// Останавливаем все горутины
	log.Println("Agent is stopping")
	cancel()

	// Ждём завершения всех горутин
	wg.Wait()
```

2024-07-19 00:33 UTC, vokinneberg commented on cmd/skill/main.go
> +	if request.Method != http.MethodPost {
А как вообще это используется? Это какой-то отдельный бинарник? А для чего он нужен?

2024-07-19 00:33 UTC, vokinneberg commented on internal/metrics/MemStorage.go
> +func (storage *MemStorage) SetGauge(name string, value Gauge) {
Справедливо.

2024-07-19 09:03 UTC, Fairness2 commented on cmd/agent/config/env.go
> +var ServerURL = "http://localhost:8080"
В константах убрал приведение к Duration

2024-07-19 09:06 UTC, Fairness2 commented on cmd/agent/config/env.go
> +func Parse() {
Глобальные константы используются теперь для значений по умолчанию. Сам конфиг заполняется в структуру, которая заполняется по правилам окружение>командная строка>значения по умолчанию

2024-07-19 09:06 UTC, Fairness2 commented on cmd/agent/config/env.go
> +		log.Print(err)
Теперь ошибка возвращается на верхний уровень и решения принимаются там

2024-07-19 09:07 UTC, Fairness2 commented on cmd/agent/config/env.go
> +		_ = setServerURL(cnf.ServerURL)
Теперь ошибка не игнорируется

2024-07-19 09:08 UTC, Fairness2 commented on cmd/agent/collector/main.go
> +package collector
переименовано

2024-07-19 09:09 UTC, Fairness2 commented on cmd/agent/collector/main.go
> +func collectProcess() {
Использован контекст для выхода

2024-07-19 09:10 UTC, Fairness2 commented on cmd/agent/collector/collection/collection.go
> +func (c *CollectionType) UnlockRead() {
Сделан обычный мютекс, который блокируется при любом обновлении, а так как у нас при чтении сбрасывается каунтер, то блокируем и тогда

2024-07-19 09:10 UTC, Fairness2 commented on cmd/agent/collector/collection/collection.go
> +func init() {
Метод init больше не используется для инициализации значений

2024-07-19 09:10 UTC, Fairness2 commented on cmd/agent/collector/main.go
> +	fmt.Println("New sender client created")
Перевёл всё на log

2024-07-19 09:11 UTC, Fairness2 commented on cmd/agent/collector/collection/collection.go
> +	fmt.Println("End collecting metrics")
Перевёл всё на лог

2024-07-19 09:11 UTC, Fairness2 commented on cmd/agent/collector/sender/sender.go
> +func (c *Client) StartSender() {
Убрал дополнительные обёртки над стартами потоков, теперь они явно вызываются в main

2024-07-19 09:12 UTC, Fairness2 commented on cmd/agent/collector/sender/sender.go
> +	v := reflect.Indirect(reflect.ValueOf(c.metricsCollection))
Убрал использование рефлексии, а метрики перевёл на использование мапы

2024-07-19 09:12 UTC, Fairness2 commented on cmd/agent/collector/sender/sender_test.go
> +			name: "invalid http status",
Поправил названия тестов

2024-07-19 09:13 UTC, Fairness2 commented on cmd/agent/collector/sender/sender_test.go
> +			name: "successful metric send",
Заменил пробелы на нижнее подчёркивание

2024-07-19 09:14 UTC, Fairness2 commented on cmd/server/config/config.go
> +func Parse() {
Глобальные константы используются теперь для значений по умолчанию. Сам конфиг заполняется в структуру, которая заполняется по правилам окружение>командная строка>значения по умолчанию

2024-07-19 09:14 UTC, Fairness2 commented on cmd/server/main.go
> +		panic(err)
Переделал на log.Fatalf

2024-07-19 09:15 UTC, Fairness2 commented on internal/metrics/MemStorage_test.go
> +		wantValue interface{}
Заменил interface{} на any

2024-07-19 09:16 UTC, Fairness2 commented on internal/metrics/MemStorage.go
> +type Storage interface {
Перенёс интерфейс и глобальную переменную в отдельный файл internal/metrics/storage.go, где они используются

2024-07-19 09:18 UTC, Fairness2 commented on internal/metrics/MemStorage.go
> +func init() {
Метод init больше не используется, NewMemStorage отдаёт новое хранилище для использования вышестоящими функциями

2024-07-19 09:19 UTC, Fairness2 commented on internal/helpers/helpers_test.go
> +			defer result.Body.Close()
Перенёс функцию выше, сразу после получения

2024-07-19 09:19 UTC, Fairness2 commented on cmd/skill/main_test.go
> +		{method: http.MethodGet, expectedCode: http.StatusMethodNotAllowed, expectedBody: ""},
Добавил названия для тестов

2024-07-19 09:21 UTC, Fairness2 commented on cmd/skill/main.go
> +	if request.Method != http.MethodPost {
В уроках в конце каждой главы перед инкрементом даётся пример по пройденному материалу на примере разработки навыка для алисы. Считается отдельным третьим приложением после агента и сервера

2024-07-19 09:24 UTC, Fairness2 commented on cmd/agent/collector/collection/collection.go
> +	mutex *sync.Mutex
Оставил так в агенте, так как у нас при чтении всё равно идёт запись в коллекцию, мы сбрасываем каунтер сбора метрик. Так как агент у нас пока не запускает кучу потоков по сбору, а только 2 потока, один для отправки, второй для сбора, то блокировка не должна приносить много проблем. В дальнейшем можно будет вернуться к этому в теме конкурентности/многопоточности.

2024-07-19 09:27 UTC, Fairness2 commented on cmd/agent/config/env.go
> +func InitializeNewCliConfig() *CliConfig {
Переименовал в InitializeDefaultConfig (будет видно в инкременте следующего спринта). Изначальное название было оправданным, когда мы создавали конфиг только из аргументов командной строки, с применением окружения название потеряло свой первоначальный смысл

2024-07-19 09:30 UTC, Fairness2 commented on cmd/agent/config/env.go
> +var Params *CliConfig
Тоже думаю, что глобальные переменные не хорошо. Но пока не придумал как сделать лучше без значительного усложнения. 
Может как-то использовать контекст? 
Конфигурация всего приложения, в Java и PHP такая конфигурация тоже получается их определённого глобального контекста🤔

2024-07-19 09:34 UTC, Fairness2 commented on cmd/agent/collector/collection/initializer.go
> +	}
Переделал с time.After (изменение будет в мерже следующего спринта). Выглядит дейтсвительно лучше. Использовал слип, так как его пока рекомендовали в задании по инкременту

2024-07-19 09:41 UTC, Fairness2 commented on cmd/agent/main.go
> +	wg.Wait() // Ожидаем завершения всех горутин
Пока оставил таймаут, но добавил выход по Ctrl+C. Получилось так, что либо заканчивается таймер, либо закрывается приложение
`
ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second) // Таймер, чтобы ограничить время работы агента, чтобы пройти тесты
	defer cancel()
	// Создаём группу ожидания на 2 потока: сборки данных и отправки
	wg := sync.WaitGroup{}
	wg.Add(2)
	go func() {
		collection.CollectProcess(ctx)
		defer wg.Done()
	}() // Запускаем сборку данных

	// Запускаем отправку данных
	client := sender.NewSender(collection.Collection)
	log.Println("New sender client created")
	go func() {
		client.PeriodicSender(ctx)
		defer wg.Done()
	}()
	// Ожидаем сигнала завершения Ctrl+C, чтобы корректно завершить работу
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, syscall.SIGINT, syscall.SIGTERM)
	select {
	case <-stop:
		cancel()
	case <-ctx.Done():
		// continue
	}
	log.Println("Agent is stopping")
	wg.Wait() // Ожидаем завершения всех горутин
	log.Println("Agent stopped")
`
Будет в мерже следующего спринта

2024-07-19 09:44 UTC, merged