Инкремент 9
Fairness2/gmetrics pull request #9
Opened 2024-07-23 18:47 UTC by Fairness2

Добавлено сжатие GZIP для сервера и клиента. Добавил хранилище с записью в файл. API переведено на JSON на сервере и агенте. Добавлено логирование на серере с помощью ZAP

2024-08-02 02:24 UTC, vokinneberg requested changes
Поздравляю с первым ревью второго спринта! 🤗  В этом спринте мы охватили большой и важный материал, а наше приложение усложнилось. 💪 Ты справился с реализацией и реализовал все в соотвествии с постановкой задачи. Отличная работа! 🚀 Тем не менее мне хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓 Так же предлагаю запланировать встречу 1 на 1, где мы могли бы обсудить review 🤝

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Ты реализовал тесты новых сценариев и дополнил существущие. 👍
3. Ты реализовал graceful shutdown для клиента и сервера и разобрался с синхронизацией горутин и работой с каналами и Wait группами. Очень круто 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Стоит поправить 30 секундный таймаут в клиенте - это основаная проблема, которую я вижу в твоем коде.
2. Мне показалось, что реализация запуска сервера и graceful shutdown  реализованы немного сложно и эту часть можно было бы упростить. Не стоит злоупотреблять вызовом горутин и стоит помнить о том, что конкурентный код  сложнее отлаживать и понимать.

2024-08-02 02:24 UTC, vokinneberg commented on cmd/agent/collector/collection/initializer.go
> +	collect()
👍 за переработку этой функции.

2024-08-02 02:24 UTC, vokinneberg commented on cmd/agent/collector/collection/initializer.go
> +func collect() {
👍 за реализацию отдельной функции сбора метрик.

2024-08-02 02:24 UTC, vokinneberg commented on cmd/agent/collector/sender/sender.go
> +	<-time.After(1 * time.Second)
Мне не кажется такой подход достаточно надежным. Что произойдет, если по какой-то причине метрики не будут собраны за 1 секунду? Думаю тут стоит подумать о том, как реализовать первую отправку метрик гарантировано после того, как они будут собраны?

2024-08-02 02:24 UTC, vokinneberg commented on cmd/agent/collector/sender/sender.go
> +		err := c.sendMetric(body)
Видимо я не заметил этого поведения во время проверки предидущего инкремента, но тут я вижу потенциальную проблему с тем, что счетчик `c.metricsCollection.ResetCounter()` будет сброшен до того, как метрики будут отправлены. Возможно вызов горутины тут лишний и синхронная отправка метрик позволит упростить логику.

2024-08-02 02:24 UTC, vokinneberg commented on cmd/agent/collector/sender/sender.go
> +	// Создаём буфер, в который запишем сжатое тело
Если хочется оптимизировать выделение памяти можно посмотреть в сторону `sync.Pool`. 

```go
 var gzipWriterPool = sync.Pool{
	New: func() interface{} {
		writer, _ := gzip.NewWriterLevel(nil, gzip.BestSpeed)
		return writer
	},
}
```

И вместо создания буфера получать инстанс из пула:

```go
        var buf bytes.Buffer
	writer := gzipWriterPool.Get().(*gzip.Writer)
	defer gzipWriterPool.Put(writer)
```

2024-08-02 02:24 UTC, vokinneberg commented on cmd/agent/config/env.go
> +const (
Рекомендую поднять `const` блок на верх файла сразу после определения импортов, это более ковенциональное место для определения констант.

2024-08-02 02:24 UTC, vokinneberg commented on cmd/agent/main.go
> +	config.Params = cnf
Я по-моему об этом уже писал - не понятно зачем нам ограничивать работу клиента 30 секундами. Мне кажется тут нужно создать не таймаут контекст, а контекст с отменой:

```go
    ctx, cancel := context.WithCancel(context.Background())
```

2024-08-02 02:24 UTC, vokinneberg commented on internal/logger/middleware.go
> +func LogRequests(next http.Handler) http.Handler {
Все-таки по условию задачи логирование запросов и ответов должно быть реализовано в виде одного middleware хендлера, который сначала логирует запрос, а потом ответ. Мне кажется, это принципиально с точки зрения понимания работы хендлера.

2024-08-02 02:24 UTC, vokinneberg commented on internal/logger/middleware.go
> +		defer func() {
Здесь логирование запроса произойдет после обработки запроса, мне кажется это не совсем то чего мы хотим добиться?

2024-08-02 02:24 UTC, vokinneberg commented on internal/logger/skill/logger.go
> +func Initialize(level string) error {
Мне кажется этот код как минимум дублирует код в файле `internal/logger/logger.go`. Можем ли мы сделать общую реализацию инициализации логгера?

2024-08-02 02:24 UTC, vokinneberg commented on cmd/server/config/parse.go
> +	cnf := struct {
Мы уже определили такую же структуру в файле `cmd/server/config/config.go`. Можем ее тут переиспользовать?

2024-08-02 02:24 UTC, vokinneberg commented on cmd/server/config/parse.go
> +	}
Не совсем понятна логика иницализации? Зачем поверять `os.LookupEnv("RESTORE")`, но при этом устанавливать `params.Restore = cnf.Restore`? Не проще ли просто установить значением сразу равным `cnf.Restore`?
 
```suggestion
	params.Restore = cnf.Restore
```

2024-08-02 02:24 UTC, vokinneberg commented on cmd/server/main.go
> +func InitStore(n next, ctx context.Context, wg *sync.WaitGroup) {
По конвенции Go, контекст передается как первый параметр функции.

```suggestion
func InitStore(ctx context.Context, n next,  wg *sync.WaitGroup) {
```

2024-08-02 02:24 UTC, vokinneberg commented on cmd/server/main.go
> +	InitLogger(func() {
Не совсем понятно, какую задачу решает такой последовательный вызов функций?  По-моему код стало сложнее понимать, при этом просто последовательный вызов функций решил ту же задачу без проблем.

2024-08-02 02:24 UTC, vokinneberg commented on cmd/server/main.go
> +		wg.Wait() // Ожидаем завершения всех горутин перед завершением программы
Я бы не рекомендовал вызывать `wg.Wait()` в `defer` блоке, так как это неявно - логика же `wg.Wait()` предполагает явную блокировку и ожидание на ней.

2024-08-02 02:24 UTC, vokinneberg commented on cmd/server/main.go
> +				defer wg.Done()
`defer` должен вызываться как можно раньше после входа в функцию. Если краш произойдет в `store.Sync(ctx)` defer ни когда не выполнится.

```suggestion
				defer wg.Done()
				store.Sync(ctx)
```

2024-08-02 02:24 UTC, vokinneberg commented on cmd/skill/main_test.go
> +		require.NoError(t, err)
Было бы здорово добавить информативные сообщения о том, что пошло не так и что ожидалось.

2024-08-02 02:24 UTC, vokinneberg commented on cmd/skill/main.go
> +func gzipMiddleware(h http.Handler) http.Handler {
Можем ли мы использовать те же middleware, которые используем для сервера?

2024-08-02 02:24 UTC, vokinneberg commented on internal/metrics/FileStorage.go
> +}
Здесь можно попробовать использовать комбинацию интерфейсов и исользовать уже существующий интерфейс из пакета `io`.

```suggestion
type Writer interface {
	Write(v any) error
	io.Closer
}
```

2024-08-02 17:51 UTC, Fairness2 commented on cmd/agent/collector/sender/sender.go
> +		err := c.sendMetric(body)
Возможно данные не придут последовательно и каунтер может прийти раньше некоторых метрик. В данном случае данные метрики не изменятся при отправке в горутинах, так как передаются по значению, а не по ссылке 🤔

2024-08-02 17:55 UTC, Fairness2 commented on cmd/agent/collector/sender/sender.go
> +		err := c.sendMetric(body)
В третьем спринте отправка будет изменена на метод, где все метрики отправляются разом, может там и переделать?

2024-08-02 18:22 UTC, Fairness2 commented on cmd/agent/config/env.go
> +const (
Перенёс всё выше

2024-08-02 18:23 UTC, Fairness2 commented on cmd/agent/collector/sender/sender.go
> +	// Создаём буфер, в который запишем сжатое тело
Переделал на Pool

2024-08-02 18:29 UTC, Fairness2 commented on internal/logger/middleware.go
> +func LogRequests(next http.Handler) http.Handler {
Объединил LogRequests и LogResponse

2024-08-02 18:30 UTC, Fairness2 commented on internal/logger/middleware.go
> +		defer func() {
Данные о времени выполнения запроса, статусе и размере ответа можно записать только после выполнения

2024-08-02 18:39 UTC, Fairness2 commented on internal/logger/skill/logger.go
> +func Initialize(level string) error {
Сделал общую реализацию. Но вообще, всё что связано с skill основано на примерах, что написаны в конце глав, где рассказывается пример создания навыка для Алисы. Было написано, что можно их делать и на основной проект не повлияет)

2024-08-02 18:44 UTC, Fairness2 commented on cmd/server/config/parse.go
> +	cnf := struct {
Не получается, так как при использовании типа time.Duration библиотека предполагает, что время в секундах будет передано в виде 23s, то есть с мерой времени, а по постановке задачи требуется прописывать 23 просто, поэтому в этой структуре используется int. Если бы не это требование, то можно было бы использовать структуру из config.go

2024-08-02 18:47 UTC, Fairness2 commented on cmd/server/config/parse.go
> +	}
Тут я так сделал, чтобы мы могли поменять значение по умолчанию в константе, там же где все остальные значения по умолчанию. Иначе, при изменении значения по умолчанию, если не указывать, RESTORE, то будет записано значение по умолчанию из структуры для парсинга

2024-08-02 19:06 UTC, Fairness2 commented on cmd/server/main.go
> +	InitLogger(func() {
Идея была в том, чтобы вынести инициализацию компонентов в отдельные функции, Переделал по другому, но теперь дефер функция по закрытию хранилища в другой функции

2024-08-02 19:12 UTC, Fairness2 commented on cmd/server/main.go
> +		wg.Wait() // Ожидаем завершения всех горутин перед завершением программы
Вынес всё что использует группу в отдельную функцию, а в мэйне оставил только ожидание

2024-08-02 19:12 UTC, Fairness2 commented on cmd/server/main.go
> +				defer wg.Done()
Поправил

2024-08-03 10:16 UTC, Fairness2 commented on cmd/agent/collector/sender/sender.go
> +	<-time.After(1 * time.Second)
Теперь первая отправка будет по таймеру

2024-08-03 10:21 UTC, Fairness2 commented on cmd/agent/collector/sender/sender.go
> +		err := c.sendMetric(body)
В данном случае отправляемые данные не будут изменены, так как будут переданы по значению. В третьем спринте будет переделано на отправку пакетом. Пока сделал группу ожидания, чтобы сбросить каунтер только после отправки всех метрик

2024-08-03 10:22 UTC, Fairness2 commented on cmd/agent/collector/sender/sender.go
> +	// Создаём буфер, в который запишем сжатое тело
Сделал группу врайтеров для отправки

2024-08-03 10:23 UTC, Fairness2 commented on cmd/agent/main.go
> +	config.Params = cnf
УБрал, вроде теперь тесты проходят)

2024-08-03 10:24 UTC, Fairness2 commented on cmd/server/main.go
> +func InitStore(n next, ctx context.Context, wg *sync.WaitGroup) {
Перенёс и упростил функции

2024-08-03 10:25 UTC, Fairness2 commented on cmd/server/main.go
> +		wg.Wait() // Ожидаем завершения всех горутин перед завершением программы
Переделал этот момент, вынес код в новую функцию, которая вызывается и группа ожидает в конце вызывающей функции теперь

2024-08-03 10:25 UTC, Fairness2 commented on cmd/server/main.go
> +				defer wg.Done()
Перенёс

2024-08-03 10:30 UTC, Fairness2 commented on cmd/skill/main_test.go
> +		require.NoError(t, err)
Добавил информационные сообщения

2024-08-03 10:31 UTC, Fairness2 commented on cmd/skill/main.go
> +func gzipMiddleware(h http.Handler) http.Handler {
Переделал на использование одних мидлварей

2024-08-03 10:31 UTC, Fairness2 commented on internal/metrics/FileStorage.go
> +}
Добавил интерфейс io.Closer

2024-08-08 04:05 UTC, vokinneberg commented on cmd/agent/collector/sender/sender.go
> +		err := c.sendMetric(body)
ОК, давай оставим вопрос на 3 спринт 👍

2024-08-08 04:06 UTC, vokinneberg commented on internal/logger/middleware.go
> +func LogRequests(next http.Handler) http.Handler {
Здорово, спасибо! 👍

2024-08-08 04:08 UTC, vokinneberg commented on internal/logger/middleware.go
> +		defer func() {
В целом оба подхода валидны. Я имел ввиду то, что если мы залогируем данные запроса до того, как он будет обработан, то в случае сбоя у нас останется лог запроса хотя бы.

2024-08-08 04:09 UTC, vokinneberg commented on internal/logger/skill/logger.go
> +func Initialize(level string) error {
Я стараюсь комментировать весь код. На проект это не влияет, но мне кажется даже в опциональном коде следует следовать лучшим практикам, так сказать набивать руку 😊

2024-08-08 04:23 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью второго спринта! 🤗 Ты реализовал многие из моих предложений. Здорово! Мне кажется, удалось упростить некоторые моменты, и код стал понятнее. У нас остался открытый вопрос относительно сброса счетчика, я предлагаю обсудить его на 3 спринте. 🤝

2024-08-08 04:23 UTC, vokinneberg commented on cmd/server/config/parse.go
> +	cnf := struct {
А что нам мешает там использовать тип int? Мне кажется, что если будет единобразно, будет только лучше?

2024-08-08 05:49 UTC, Fairness2 commented on internal/logger/middleware.go
> +		defer func() {
В третьем спринте попробую переделать

2024-08-08 05:52 UTC, Fairness2 commented on cmd/server/config/parse.go
> +	cnf := struct {
Подумаю как это решить

2024-08-08 05:54 UTC, merged